### ISSUE TITLE
Output path of manual commands are not inline with automatic commands

### ISSUE THREAD

**Issue by kehrijksen** [Tib3rius/AutoRecon#114]
Output from automatic scans are put in directories according to their ports. For instance:
scans/tcp80/tcp_80_http_curl.html
scans/tcp80/tcp_80_http_feroxbuster_big.txt

Now the manual commands for the same service have their output paths set to the scans directory, such as:
scans/tcp_80_http_nikto.txt
scans/tcp_80_http_wpscan.txt

My solution, make it consistent and set it to:
scans/tcp80/tcp_80_http_nikto.txt
scans/tcp80/tcp_80_http_wpscan.txt

**Comment by Tib3rius** [comment]
This is definitely a bug, I'll make sure to fix in the next release. Thank you!

**Comment by kehrijksen** [comment]
Maybe you could also remove the prefix now then:
scans/tcp80/tcp_80_http_nikto.txt
scans/tcp80/tcp_80_http_wpscan.txt

Can become:
scans/tcp80/http_nikto.txt
scans/tcp80/http_wpscan.txt

Or:
scans/tcp80/nikto.txt
scans/tcp80/wpscan.txt
