### ISSUE TITLE
SMBClient fails to access shares

### ISSUE THREAD

**Issue by trb143** [Tib3rius/AutoRecon#117]
Running TryHackme AllSignsPoint2Pwnage  the SMBClient request generated was 

smbclient -L\\ -N -I 10.10.31.223  which produced a tree connect failed: NT_STATUS_INVALID_PARAMETER error.

Changing the request to 

smbclient -L 10.10.31.223 -N  generated the correct result and the correct output.

This is the latest version of Autorecon and it is run as Autorecon IP address --single-target.

**Comment by Tib3rius** [comment]
Fixed in cfac135cc
