### ISSUE TITLE
Missing Service name

### ISSUE THREAD

**Issue by trb143** [Tib3rius/AutoRecon#118]
TryHackMe - Year of the pig produced the following message

AutoRecon identified the following services, but could not match them to any plugins based on the service name. Please report these to Tib3rius: tcp/22/tcpwrapped/insecure

**Comment by kehrijksen** [comment]
I have one too, from HackTheBox's Return

> [!] AutoRecon identified the following services, but could not match them to any plugins based on the service name. Please report these to Tib3rius: udp/123/ntp/insecure, tcp/593/ncacn_http/insecure, tcp/636/tcpwrapped/insecure, tcp/3269/tcpwrapped/insecure, tcp/9389/mc-nmf/insecure, tcp/49670/ncacn_http/insecure
