### ISSUE TITLE
ImportError: cannot import name 'final'

### ISSUE THREAD

**Issue by bcnx** [Tib3rius/AutoRecon#126]
Hi,

I have this error message when starting autorecon on a Raspberry Pi:

ImportError: cannot import name 'final' from 'typing' (/usr/lib/python3.7/typing.py).

Google suggests using Python 3.8 while the Pi has Python 3.7.3

What would be the best solution to this?

Thanks!

BC

**Comment by Tib3rius** [comment]
Unfortunately I don't believe there is a solution other than installing Python 3.8 manually on the Pi.
