### ISSUE TITLE
AutoRecon doesn't run Nikto anymore

### ISSUE THREAD

**Issue by heyquentin** [Tib3rius/AutoRecon#127]
I'm using AutoRecon v2.0.5 and it's not running Nikto anymore. I've got an older version of AutoRecon installed and it runs Nikto against the machine I'm scanning but v2.0.5 doesn't. Am I doing something wrong or do I have to manually select it or something?

**Comment by heyquentin** [comment]
Oh wow, I think I figured out how to fix it. I added the following lines to /home/kali/.config/AutoRecon/plugins/http_server.py under the class Nikto
```
	# Added these lines to make Nikto run
	async def run(self, service):
		if service.protocol == 'tcp' and service.target.ipversion == 'IPv4':
			await service.execute('nikto -ask=no -h {http_scheme}://{address}:{port} 2>&1 | tee "{scandir}/{protocol}_{port}_{http_scheme}_nikto.txt"')
```

The whole class Nikto now looks like this
```
class Nikto(ServiceScan):

	def __init__(self):
		super().__init__()
		self.name = 'nikto'
		self.tags = ['default', 'safe', 'long', 'http']

	def configure(self):
		self.match_service_name('^http')
		self.match_service_name('^nacn_http$', negative_match=True)

	# Added these lines to make Nikto run
	async def run(self, service):
		if service.protocol == 'tcp' and service.target.ipversion == 'IPv4':
			await service.execute('nikto -ask=no -h {http_scheme}://{address}:{port} 2>&1 | tee "{scandir}/{protocol}_{port}_{http_scheme}_nikto.txt"')
	
	def manual(self, service, plugin_was_run):
		if service.target.ipversion == 'IPv4':
			service.add_manual_command('(nikto) old but generally reliable web server enumeration tool:', 'nikto -ask=no -h {http_scheme}://{address}:{port} 2>&1 | tee "{scandir}/{protocol}_{port}_{http_scheme}_nikto.txt"')
```

I tested it and it looks like Nikto ran. Neat!

**Comment by Tib3rius** [comment]
Hi @heyquentin,

Yeah, nikto was removed from the automated commands in v2, mostly because the tool takes so long, but also because it's highly outdated and other tools do practically the same thing (e.g. nmap scripts, gobuster, etc.)

Your way of enabling it is correct. Plugins with a run() function will run automatically. :)

**Comment by heyquentin** [comment]
Awesome! Super appreciate the confirmation. Love the tool and your Udemy courses. Cheers 👍
