### ISSUE TITLE
AutoRecon identified the following services, but could not match them to any plugins based on the service name

### ISSUE THREAD

**Issue by tieupham267** [Tib3rius/AutoRecon#130]
I'm get the notice from autorecon when scan the hack-the-box Sunday.
My command is: _python3 autorecon.py 10.10.10.76 -o /root/OSCP/HTB/_
I hope my report is helpful for you to improve autorecon.

[!] AutoRecon identified the following services, but could not match them to any plugins based on the service name. Please report these to Tib3rius: tcp/48837/unknown/insecure, tcp/60544/unknown/insecure

**Comment by Tib3rius** [comment]
Thanks, this was a bug. Fixed in the latest release.
