### ISSUE TITLE
Directory Buster ignoring config file

### ISSUE THREAD

**Issue by Fittoni** [Tib3rius/AutoRecon#132]
Hey, maybe im doing something wrong but in the config.toml I have dirbuster set to only scan these wordlists:

```
# Configure plugin options here.
[dirbuster]
# threads = 50
wordlist = ['/usr/share/seclists/Discovery/Web-Content/common.txt','/usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt']
```

But when I execute the script it is still using some bigger files: 

``` bash
[*] Service scan Directory Buster (tcp/443/http/dirbuster) is running the following command against 10.10.10.250: feroxbuster -u https://10.10.10.250:443/ -t 10 -w /usr/share/seclists/Discovery/Web-Content/big.txt -x "txt,html,php,asp,aspx,jsp" -v -k -n -q -o "/mnt/d/HTB/results/10.10.10.250/scans/tcp443/tcp_443_https_feroxbuster_big.txt"
[*] Service scan Directory Buster (tcp/8080/http-proxy/dirbuster) is running the following command against 10.10.10.250: feroxbuster -u http://10.10.10.250:8080/ -t 10 -w /usr/share/seclists/Discovery/Web-Content/big.txt -x "txt,html,php,asp,aspx,jsp" -v -k -n -q -o "/mnt/d/HTB/results/10.10.10.250/scans/tcp8080/tcp_8080_http_feroxbuster_big.txt"`
```

Except from that this is an awesome tool, I'm still trying to change the configs to my need, like changing the nmap scan's etc. 
Thanks for your effort!

**Comment by Tib3rius** [comment]
Interesting. Are you referencing the config file using -c in your AutoRecon command?

There are three ways in which AutoRecon attempts to find a config file:

1. If -c is set, then it uses the config file specified there.
2. If -c is not set, it checks to see if there is a config file in the current directory. If there is, it uses that.
3. If there is no config file in the current directory, it will use the one located at ~/.config/AutoRecon/config.toml

What might be happening is you're changing a config file but it's not the one AutoRecon is actually using. Could you try using -c (if you aren't already) and letting me know if you encounter the same issue?

Thanks!

**Comment by Fittoni** [comment]
No i did not reference the config file. I changed the file in ~/.config/AutoRecon/config.toml and did not create another one.
If I use -c and reference the file, it is working.
I will try again now without -c, maybe there was something wrong with the file.

**Comment by Fittoni** [comment]
Okay so without -c it's taking the big wordlist again.
```
feroxbuster -u http://10.10.10.250:8080/ -t 10 -w /usr/share/seclists/Discovery/Web-Content/big.txt -x "txt,html,php,asp,aspx,jsp" -v -k -n -q -o "/mnt/d/HTB/results/10.10.10.250/scans/tcp8080/tcp_8080_http_feroxbuster_big.txt"
```

If you can't reproduce it, I will reinstall it tomorrow and check again. Thanks for your help!

**Comment by Tib3rius** [comment]
Hi @Fittoni,

I haven't been able to reproduce the error. When I change the wordlist config option in ~/.config/AutoRecon/config.toml, and run AutoRecon from a directory with no config.toml, it doesn't use big.txt.

One thought occurred to me. Are you running AutoRecon with sudo? If so, it's the /root/.config/AutoRecon.config.toml file you'd have to change. That's the only thing that makes sense to me.

Otherwise yes, please reinstall and make sure there's no errant config.toml file in the directory you run it from. Let me know how it goes.

**Comment by Fittoni** [comment]
Hi @Tib3rius 
Oh yes, you are right that was the problem. I'm sorry should have noticed that. It's working now as expected.

**Comment by Tib3rius** [comment]
@Fittoni no worries, glad it's working!
