### ISSUE TITLE
Gobuster showing up as a required supporting package

### ISSUE THREAD

**Issue by billyball1517** [Tib3rius/AutoRecon#137]
Hello,

I just updated autorecon via pipx and now autorecon won't run unless gobuster is installed.

Issues can be replicated with fresh install

![image](https://user-images.githubusercontent.com/54004311/148889605-8102b6d0-564e-495c-bee1-feb5e3601358.png)
![image](https://user-images.githubusercontent.com/54004311/148889704-ce770276-891b-4d25-9c46-28b08c182837.png)

**Comment by Tib3rius** [comment]
Thanks, I thought gobuster was installed by default. The new readme has gobuster in the install list.
