### ISSUE TITLE
Gobuster 3.x

### ISSUE THREAD

**Issue by bajaguy** [Tib3rius/AutoRecon#14]
New version of gobuster uses Modes (https://github.com/OJ/gobuster#available-modes).

From _manual_commands.txt:
gobuster dir -u http://172.16.1.23:80/ -w /usr/share/seclists/Discovery/Web-Content/big.txt -e -k -l -s "200,204,301,302,307,403,500" -x "txt,html,php,asp,aspx" -o "/root/labs/172.16.1.23/scans/tcp_80_http_gobuster_big.txt"

Produces the following error:
Error: unknown command "200,204,301,302,307,403,500" for "gobuster"
Run 'gobuster --help' for usage.

Modifying the command with 'dir' after gobuster works fine:
gobuster dir -u http://172.16.1.23:80/ -w /usr/share/seclists/Discovery/Web-Content/big.txt -e -k -l -s "200,204,301,302,307,403,500" -x "txt,html,php,asp,aspx" -o "/root/labs/172.16.1.23/scans/tcp_80_http_gobuster_big.txt"

**Comment by Tib3rius** [comment]
Thanks for alerting me. I don't see a good solution to this, however. Terrible design decision not to make gobuster backwards compatible, to be honest. I may have to remove gobuster from the automatic scan as several people on the OSCP build of Kali (which still uses gobuster 2, to my knowledge) will run into errors if I make the change.

**Comment by AaronDhiman** [comment]
yes, 2019.2 OffSec kali still on v2:

root@kali:~# apt list gobuster --installed
Listing... Done
gobuster/now 2.0.1-1 amd64 [installed,upgradable to: 3.0.1-0kali1]

**Comment by michelangelo-sarafis** [comment]
> 
> 
> Thanks for alerting me. I don't see a good solution to this, however. Terrible design decision not to make gobuster backwards compatible, to be honest. I may have to remove gobuster from the automatic scan as several people on the OSCP build of Kali (which still uses gobuster 2, to my knowledge) will run into errors if I make the change.

Why not replacing GoBuster with dirb ? Has the same functionalities as GoBuster.

**Comment by Tib3rius** [comment]
@michelangelo-sarafis that might be the solution.

**Comment by AaronDhiman** [comment]
@michelangelo-sarafis that can be done in the config file.  I have done that in one environment where I don't have the Go language installed.

**Comment by Tib3rius** [comment]
Fixed in e35b3c4b8963b61e821f0d66d24fea58263bd8fc.
