### ISSUE TITLE
Nmap UDP scan

### ISSUE THREAD

**Issue by A1vinSmith** [Tib3rius/AutoRecon#140]
I'm scanning the HackTheBox Pandora machine. It's an active one. autorecon didn't give the 162udp port out.

Does Autorecon not scan UDP ports by default? Or It scanned but missed it?

**Comment by Tib3rius** [comment]
@A1vinSmith did you run AutoRecon as root? Only the root user can use Nmap's UDP scanning ability so AutoRecon won't run it unless you're running as root. It is a default scan however.

**Comment by A1vinSmith** [comment]
Thank you. I thought I did the alias thing. It looks like I forgot to add the path to the `/etc/sudoers` securePath.
