### ISSUE TITLE
smbmap not allowed on OSCP

### ISSUE THREAD

**Issue by PaddyAZ** [Tib3rius/AutoRecon#142]
is there a way to exclude the smbmap portion of the process? 
As a workaround I was able to remove the plugin for this but suspect it will comeback on updates.
I'm a nimrod. mixed up SQLmap which isn't an issue. Sorry.

**Comment by 1moere1** [comment]
why would smbmap be not allowed?

**Comment by anasbousselham** [comment]
smbmap is allowed, sqlmap no

**Comment by PaddyAZ** [comment]
Sorry for my mixup.
