### ISSUE TITLE
nmap without sudo

### ISSUE THREAD

**Issue by kdirectorate** [Tib3rius/AutoRecon#145]
I use this:

sudo setcap cap_net_raw,cap_net_admin,cap_net_bind_service+eip /usr/bin/nmap

and:

nmap --privileged 

To setup my box so that I don't have to sudo to run nmap. Is it possible to add an option to Autorecon to use this method instead of requiring sudo for UDP scans?

**Comment by Tib3rius** [comment]
@kdirectorate I've introduced a fix for this edge case. If you run the latest AutoRecon with `--disable-sanity-checks` it will skip the sudo / root requirement for UDP. Let me know if this works.
