### ISSUE TITLE
[!] Error: Service scan OneSixtyOne

### ISSUE THREAD

**Issue by tieupham267** [Tib3rius/AutoRecon#146]
I'm getting errors when scanning the Hack the box: Conceal.

Error details:
[!] Error: Service scan OneSixtyOne (udp/161/snmp/onesixtyone) running against 10.10.10.116 produced an exception:

  File "/root/.config/AutoRecon/plugins/onesixtyone.py", line 18, in run
    await service.execute('onesixtyone -c ' + service.get_option('community-strings') + ' -dd 10.10.10.116 2>&1', outfile='udp_161_snmp_onesixtyone.txt')
AttributeError: 'Service' object has no attribute 'get_option'

**Comment by Tib3rius** [comment]
Thanks! That was a simple typo.
