### ISSUE TITLE
AutoRecon Suggestion

### ISSUE THREAD

**Issue by sinfulz** [Tib3rius/AutoRecon#15]
Hi Tib3rius,

It would be great if AutoRecon outputted the total time the tool ran for.

Example - at the end of the scan it would say:

> Finished scanning all targets in 2000 seconds.

Cheers

**Comment by Muhammad-Daniyal-Sheikh** [comment]
Yes, that would be nice.

**Comment by Tib3rius** [comment]
Added in e9c62731447ea63dea4106976bae614b5375ff0d.
