### ISSUE TITLE
getArch.py

### ISSUE THREAD

**Issue by 45im** [Tib3rius/AutoRecon#151]
Hi @Tib3rius
impacket-getArch is installed by default on kali for a while now.
 but the script calls getArch.py instead.
Although i have local user install of impacket in my .local/bin it cannot be used by autorecon if being run as sudo or root.
some other impacket scripts are being called correctly e.g. rpcdump.py is being called as impacket-rpcdump.
regards

**Comment by 45im** [comment]
I have created a pull request.
please have a look

**Comment by Tib3rius** [comment]
Merged. Thank you!
