### ISSUE TITLE
Adding WPScan API Token

### ISSUE THREAD

**Issue by ahanel13** [Tib3rius/AutoRecon#154]
From what I can tell there is already code that can add and use the API token when the recommend wpscan is added to manual commands. I'm a confused how a user it supposed to add the token. 

There is an empty string call api_token on line 16 of wpscan.py, and it's updated with a function called "get_option" but I'm not sure how to set the api_token option.

**Comment by Tib3rius** [comment]
You can set it on the command line when you run AutoRecon like so:

`--wpscan.api-token <token>`

Or if you prefer using a config file, by adding the following to the end of the file:

```toml
[wpscan]
api-token = "<token>"
```
