### ISSUE TITLE
Make the scan speed faster

### ISSUE THREAD

**Issue by vincentchenroc** [Tib3rius/AutoRecon#157]
Hi All,

I would like to make the AutoRecon scan speed **faster**. How do I suppose to do？

ex. autorecon -m 100 -mp 20 --heartbeat 300 -vv --single-target X.X.X.X

Could you share the command for the reference？

**Comment by Tib3rius** [comment]
@vincentchenroc if you're talking about Nmap scan speed, then you can do this easily using the --nmap-append option, for example if you wanted Nmap to always use -T5 and --min-rate=5000 you could do the following:

```
autorecon --nmap-append="-T5 --min-rate=5000" ... X.X.X.X
```

You can also set this in the config file by adding this at the top:
```
nmap-append = '-T5 --min-rate=5000'
```
That will cover the Nmap commands, but for other things (e.g. gobuster) you'll have to look at autorecon's help output (`-h`) and there you will find options to set the threads for specific plugins:

```
--dirbuster.threads VALUE
--subdomain-enum.threads VALUE
--vhost-enum.threads VALUE
```

For any other plugins, you would have to edit the plugin file itself and change the command.
