### ISSUE TITLE
suggestion about Scanning Stage

### ISSUE THREAD

**Issue by zuesdevil** [Tib3rius/AutoRecon#164]
hi guy,
  I had a suggestion that this situation comes from the exam. Is it possible to add a caching mechanism, in order to terminate the scan when the computer has an accident. This caching is similar to hydra's cracked password. When manually paused or accidentally paused, the hydra tool checks for cached files and the tool asks the user whether to continue with the last scan...This caching mechanism helps us to skip repeating the scanning of previous results when unexpected situations occur.
  Hope you can take this advice,thanks

**Comment by Tib3rius** [comment]
Hi @zuesdevil,

Unfortunately this is likely impossible or just too hard to implement. AutoRecon doesn't do any of its own scanning, so any caching would have to be done by the tools that AutoRecon runs.

You can always use to `-p` option to only scan specific ports, and you can force AutoRecon to scan certain services using `--force-services`. Using the `--tags` and `--exclude-tags` options you can further limit the plugins which run.

**Comment by MrMatch246** [comment]
Just stumbled upon this, cant we just do this on a target basis?
aka once a target(host or subnet, basically based on the lines in the targets.txt) or even host (way more complicated, but probably possible too?) is finished, we drop a .finished file in the folder structure and if we get interrupted we yeet the currently worked on target or host(s). and if the command is executed again we check for the .finished file and skip all targets or hosts that have it present
this should be rather easy to implement and probably quite helpfull
