### ISSUE TITLE
dnsrecon is not included in the list of the packages that need to be installed for AutoRecon to work

### ISSUE THREAD

**Issue by NalZE7** [Tib3rius/AutoRecon#167]
I've faced these error messages when I tried to run AutoRecon with ```sudo `which autorecon` ``` on an Ubuntu 20.04 instance:

```
[!] [dnsrecon-brute] The program dnsrecon could not be found. Make sure it is installed. (On Kali, run: sudo apt install dnsrecon)
[!] [dnsrecon] The program dnsrecon could not be found. Make sure it is installed. (On Kali, run: sudo apt install dnsrecon)
```

I do realize that this error won't appear if I were using Kali, but I did follow the installation steps on Ubuntu (after adding Kali's official repo to sources.list to install the packages) and I got AutoRecon installed but got the above errors due to `dnsrecon` not being installed, I just did `sudo apt install dnsrecon` and it worked fine.

I made a [pull request](https://github.com/Tib3rius/AutoRecon/pull/166) with `dnsrecon` being added to the `apt install` command and the list above it in the installation steps.

**Comment by Tib3rius** [comment]
Merged. Thank you!
