### ISSUE TITLE
Enum4linux error

### ISSUE THREAD

**Issue by Shak3** [Tib3rius/AutoRecon#178]
File "/home/kali/.config/AutoRecon/plugins/enum4linux.py", line 29, in run
    if self.tool is not None:
AttributeError: 'Enum4Linux' object has no attribute 'tool'

Getting this error on a new setup, wasn't getting it on my old vm prior to wiping it.

**Comment by Shak3** [comment]
I changed self.tool to self.get_options on lines 29,30, and 32 and that fixed it.

**Comment by Tib3rius** [comment]
Thanks, have updated the plugin.
