### ISSUE TITLE
--ports parameter fails 

### ISSUE THREAD

**Issue by ssmmkkxxzz** [Tib3rius/AutoRecon#179]
$ git branch  -v
* main da718ce Fixed bug in enum4linux plugin.

$ sudo autorecon -p T:1024,1025,1026,1027,1028,1029,1030,1031,1032,1033,1034,1035,1036,1037,1038,1039,1040,1041,1042,1043,1044,1045,1046,1047,1048,1049,1050,1051,1052,1053,1054,443,48193,7019,80,8086,8088,8090,8091,8443,8444,9443 google.de
[!] Argument -p/--ports: expected one argument

**Comment by Tib3rius** [comment]
@ssmmkkxxzz I'm unable to reproduce this.

Did you originally install autorecon using sudo? It's possible the root version is out of date (pip / pipx will install it in different locations if you are running sudo). Could you run both of these commands and share the results?

```
autorecon --version
sudo autorecon --version
```

**Comment by Tib3rius** [comment]
Ah! Thanks for letting me know, glad you got it sorted!
