### ISSUE TITLE
Adding a custom service

### ISSUE THREAD

**Issue by digitaloffensive** [Tib3rius/AutoRecon#18]
Issues adding a custom service. I see in the newer release dirb is now a service that is ran during enumeration. However while trying to add gobuster as a service I get errors on load. I am using the following syntax

    [[http.scan]]
    name = 'gobuster'
    command = ['gobuster dir -u {scheme}://{address}:{port}/ -w /usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt -e -k -l -s "200,204,301,302,307,403,500"-z -o "{scandir}/{protocol}_{port}_{scheme}_gobuster_dirbuster.txt"'

**Comment by Tib3rius** [comment]
Hi @digitaloffensive, apologies for the late response, I didn't see a notification for this.

I believe the issue is the [ you have before the 'gobuster in the third line. The following should be valid:

```
[[http.scan]]
name = 'gobuster'
command = 'gobuster dir -u {scheme}://{address}:{port}/ -w /usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt -e -k -l -s "200,204,301,302,307,403,500"-z -o "{scandir}/{protocol}_{port}_{scheme}_gobuster_dirbuster.txt"'
```
