### ISSUE TITLE
Enhancement: Selectively kill/abort part of an active scan 

### ISSUE THREAD

**Issue by ShyftXero** [Tib3rius/AutoRecon#183]
in the attached screenshot something hung up and the process wouldn't respond it had been running for 20 hours. 

typically this is not the case, but there are times when it would be better to kill the dirbs after N minutes or selectively kill them. in a ctf scenario say HTTP on port 8080 is obviously a rabbit hole but HTTP on port 1337 is legit and needs to be dirbed. 

it would  ffuf and feroxbuster have a menu that can be invoked mid-scan. You can use this to manipulate or stop parts of the scan. 

Perhaps a task id (the pid) could be shown as well so operators could kill off ineffective scans

![image](https://user-images.githubusercontent.com/1275714/210101387-a06caf90-3350-408c-8d2f-4edc9e04d5fb.png)

With verbosity all the way up (-vvv) you can see the feroxbuster menu being invoked.  It would just be nice to have the pid displayed (for manually killing via kill)  or a "native" way within autorecon to kill that part of the scan quickly and avoid risking killing the wrong scan in the case of multiple feroxbusters manually
 
![image](https://user-images.githubusercontent.com/1275714/210102109-d69718fb-b54c-4810-8c01-dd2b13ceef5b.png)

it looks like here is a good spot to start looking  https://github.com/Tib3rius/AutoRecon/blob/65fc104b2d3953211d8430080360c68df4cf4c37/autorecon/main.py#L115

and here
https://github.com/Tib3rius/AutoRecon/blob/65fc104b2d3953211d8430080360c68df4cf4c37/autorecon/main.py#L782

thoughts?

**Comment by Tib3rius** [comment]
I think at the very least having the PID displayed is a great idea. How does this look? It would only appear if -vv or above is used.

![Screenshot 2022-12-30 165003](https://user-images.githubusercontent.com/48113936/210113934-9a8917cf-2484-467f-92b3-96bdb36366d5.png)

In the unlikely but entirely possible event that a plugin is running two or more processes at the same time, it should comma separate them.

I'm kinda intrigued as to how you managed to invoke feroxbuster's menu though. I thought I was intercepting all stdin input.

**Comment by ShyftXero** [comment]
nice. Thanks!
