### ISSUE TITLE
Feroxbuster still actively scanning

### ISSUE THREAD

**Issue by xyplex** [Tib3rius/AutoRecon#184]
I setup my autorecon to run for only 30 minutes and after 30 minutes Autorecon stops.

However I noticed that Feroxbuster continues to run in the background and I have to kill the Feroxbuster process.

I would assume that after setting Autorecon to stop after 30 minutes that it should kill all processes that Autorecon has started?

**Comment by Tib3rius** [comment]
Nice find! It looks like the way I'm killing processes isn't killing the child process properly. Thanks, I'll work on this and get it patched.
