### ISSUE TITLE
Autorecon ability to run in background

### ISSUE THREAD

**Issue by codevallsma** [Tib3rius/AutoRecon#187]
Hello @Tib3rius !

I have been playing around with your tool and I think it's awesome! 
I really like it and i would love to use it more, however when I try to execute it in background with nohup i get the following error:
```python:
Traceback (most recent call last):
  File "/myuser/.local/bin/autorecon", line 5, in <module>
    from autorecon.main import main
  File "/myuser/.local/pipx/venvs/autorecon/lib/python3.10/site-packages/autorecon/main.py", line 53, in <module>
    terminal_settings = termios.tcgetattr(sys.stdin.fileno())
termios.error: (25, 'Inappropriate ioctl for device')
```
Could you try to fix this?

Thanks in advance! :)

**Comment by Tib3rius** [comment]
@codevallsma could you check out this branch (https://github.com/Tib3rius/AutoRecon/tree/background-fix) and see if this fixes it?

**Comment by kirov70** [comment]
Unfortunately, the fix didn't work for me. 
Thanks @codevallsma, this has been a really annoying issue for me.

**Comment by Tib3rius** [comment]
@kirov70 @codevallsma sorry I must have been half asleep when I posted, I didn't include the instruction that you need to run AutoRecon with `--disable-keyboard-control` on the new branch. That should hopefully work because it prevents that troublesome code from ever running. Can you check again?

**Comment by kirov70** [comment]
you got it, that was the issue. 
@Tib3rius Thank you very much for this fix. I do a lot of scans via ssh and the remote disconnects were killing me.
