### ISSUE TITLE
pip3 install -r requirements crashes OSCP student vm

### ISSUE THREAD

**Issue by redxking** [Tib3rius/AutoRecon#19]
So I have attempted to do this 5 times now. every time I install pip3 I get a corrupted file which causes any HTTP method to crash, which then causes my system to not even allow me to recover.

**Comment by Tib3rius** [comment]
Hi @redxking,

Please try running the following to install pip3 without touching apt:

```bash
$ curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
$ python3 get-pip.py
```

You should then be able to use pip3 as per usual.
