### ISSUE TITLE
Failed enumeration directory + vhost

### ISSUE THREAD

**Issue by ShaanksM** [Tib3rius/AutoRecon#192]
Bonjour,

I dont know why, but when i use autorecon in boxe hack the box the enumeration never passes
I find it a shame to miss out on such a tool.

the probleme is that it does not list..

i did   "autorecon -c ~/config.toml mentorquotes.htb"

e.g directory enumeration (same probeleme for vhost) : 

$ cat tcp_80_http_mentorquotes.htb_vhosts_subdomains-top1million-110000.txt
mail
whm
smtp
localhost
ftp
www
webdisk
webmail
cpanel
pop
ns1
autodiscover
ns2
test
ns
autoconfig
pop3
m
www2
dev
blog
forum
ns3
admin
mail2
mx
vpn
new
mysql
old
imap
beta
support
cp
mobile
shop
secure
demo
ns4
dns2
lists
dns1
static
web
www1
img
wiki
news
media
server
portal
images
backup
www.blog
dns
sql
intranet
www.test
www.forum
host
stats
mx1
mail1
video
www3
staging
www.m
sip
chat
crm
search
mx2
ipv4
ads
email
remote
my
wap
svn
....

can u tell me how can i fix this ? Merci

PS : I have same config.toml as you and same dnsmasq config like you (cf video of bastion.htb and love.htb)

**Comment by Tib3rius** [comment]
Fixed in a9608d6
