### ISSUE TITLE
interface option

### ISSUE THREAD

**Issue by nbandodk** [Tib3rius/AutoRecon#207]
How do i explicitly mention the interface to use while running autorecon. I have two interfaces eth0 on public ip and eth1 on private ip. I would like to route all scans through eth1. Please advise.

**Comment by Tib3rius** [comment]
The short answer is you can't, since all AutoRecon does is run other tools, some of which might support targeting specific interfaces while others will not.

You would have to add rules to the routing table for each target you need.
