### ISSUE TITLE
incorrect nmap results when scanning htb beep (10.10.10.7)

### ISSUE THREAD

**Issue by 20e8jmve** [Tib3rius/AutoRecon#33]
Not sure if you have a hack the box account, but the 10.10.10.7 box seems to do something weird causing nmap to hang which causes autorecon to miss open ports. The nmap output shows the open ports when run without autorecon.  Looking at the port-scan-profiles.toml file, adding timeout 60 and/or unbuffer to the nmap quick scan doesn't help.  After a bit of testing, the best solution I could find is to simply run autorecon with -vv
FYI

**Comment by Tib3rius** [comment]
Running AutoRecon with -vv doesn't change anything about the nmap scans being run, FYI. It simply prints out all the information returned by the nmap process to stdout.

This seems like an nmap issue rather than something to do with AutoRecon.
