### ISSUE TITLE
dependency list

### ISSUE THREAD

**Issue by meir555** [Tib3rius/AutoRecon#34]
OS: kali 2019.3 x64
uname -a:
`Linux kali 5.3.0-kali1-amd64 #1 SMP Debian 5.3.7-1kali2 (2019-11-04) x86_64 GNU/Linux`

```
root@kali:/# apt install curl enum4linux gobuster nbtscan nikto nmap onesixtyone oscanner smbclient smbmap smtp-user-enum snmpwalk sslscan svwar tnscmd10g whatweb wkhtmltoimage

Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package snmpwalk
E: Unable to locate package svwar
E: Unable to locate package wkhtmltoimage
```

/etc/apt/sources.list:
`deb http://http.kali.org/kali kali-rolling main non-free contrib`

**Comment by rayhan0x01** [comment]
Tested in Ubuntu19.10 should work on kali as well.
add to /etc/apt/sources.list:
`deb http://http.kali.org/kali kali-rolling main contrib non-free`
exec : 
`sudo apt install -y snmp sipvicious wkhtmltopdf`

**Comment by Tib3rius** [comment]
The dependency list isn't written in package format, fyi. It's a list of programs that are run as part of AutoRecon's normal operating mode.

Although it's recommended that Kali be used as the OS, I don't make assumptions about the OS, and therefore cannot list dependencies in any particular package listing. It is up to the end user to figure out how to install these programs.
