### ISSUE TITLE
line 52: SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by EanNewton** [Tib3rius/AutoRecon#35]
I have installed requirements, running on debian. When I run: sudo python autorecon.py I get the following error:

`  File "autorecon.py", line 52
    def e(*args, frame_index=1, **kvargs):
                           ^
SyntaxError: invalid syntax
`

uname -a: `Linux parrot 5.3.0-1parrot1-amd64 #1 SMP Parrot 5.3.7-1parrot1 (2019-11-04) x86_64 GNU/Linux
`

**Comment by Tib3rius** [comment]
@EanNewton are you using python3?

**Comment by Tib3rius** [comment]
Closing this as I'm pretty sure the issue was due to AutoRecon being run with python2. AutoRecon requires several features from python3 that aren't in python2, and also python2 is deprecated now so should be banished to the realms of other obsolete programming languages like Ruby and Java. ;)
