### ISSUE TITLE
AutoRecon Not Playing Song

### ISSUE THREAD

**Issue by cwinfosec** [Tib3rius/AutoRecon#38]
Hello Sir, AutoRecon doesn't play the David Hasselhoff song as shown in this demo video:

https://streamable.com/8d03v

Is my AutoRecon broken? 

(This issue was opened as a joke and not serious)

**Comment by Tib3rius** [comment]
Not sure why this was closed, this is a real issue and should be prioritized for the next development milestone.

**Comment by absane** [comment]
The whole reason I cloned this was for the song!

**Comment by Gorgamite** [comment]
say no more im on it
