### ISSUE TITLE
Finger service not scanning

### ISSUE THREAD

**Issue by deo-gracias** [Tib3rius/AutoRecon#43]
After discovering finger service, the nmap is not starting automatically
To solve it, replace 'nmap' by 'name' as following in config/service-scans.toml

 [[finger.scan]]
    **_name_** = 'nmap-finger'
    command = 'nmap {nmap_extra} -sV -p {port} --script="banner,finger" -oN "{scandir}/{protocol}_{port}_finger_nmap.txt" -oX "{scandir}/xml/{protocol}_{port}_finger_nmap.xml" {address}'

**Comment by Tib3rius** [comment]
Fixed in 42db129.
