### ISSUE TITLE
Support output into Cherrytree

### ISSUE THREAD

**Issue by Daviey** [Tib3rius/AutoRecon#45]
Hi,

It would be really good to be able to output the report into [CherryTree](https://www.giuspen.com/cherrytree/) note taking application.

A few people have tried to do similar work:

- [CherryMap](https://github.com/sergiodmn/cherrymap) - Standalone tool for taking nmap output and outputing CherryTree (recommends nmap -oA), possibly useful for integration.
- [AutoRecon-OSCP](https://github.com/VagrantSpider/AutoRecon-OSCP) - A fork of AutoRecon to do this, annoyingly with a clean git ancestry making it hard to compare the fork.  It looks like it has its own standalone tool for doing the import.  It doesn't appear to be easily maintainable, and I haven't seen an attempt to upstream the change.
- [cherrytree-nmap](https://github.com/cam-barts/cherrytree-nmap) - not looked at

There are a couple of templates for CherryTree floating around, such as https://guide.offsecnewbie.com/cherrytree-oscp-template

Thanks

**Comment by Ghostyboy0719** [comment]
That’s a great idea. I am guessing there is a template for cherry tree where the report gets pre populated! That’s easy to navigate rather than the report which is in folders

**Comment by BetaMaxHeadroom** [comment]
> This is on the roadmap for v2 with Report plugins.

After being unable to recover cherrytree files, I have moved over to Joplin for my notes. Programming is not one of my strengths. But, do you think it would be possible to also have something similar for Joplin? I can try to help. I'm just not exactly certain where to start.

**Comment by Tib3rius** [comment]
@Daviey the Cherrytree export code is in the latest beta commit.

@BetaMaxHeadroom I have a working Joplin/Obsidian export, just needs to be committed.

**Comment by g33kyshivam** [comment]
Hey @Tib3rius! Is the feature available to do an obsidian export? Also can share a flag command for a cherrytree export as well? 
Thanks :-)
