### ISSUE TITLE
Unable to run UDP scan on Kali 2020.3

### ISSUE THREAD

**Issue by crance** [Tib3rius/AutoRecon#58]
Got the following error when running autorecon.
`[!] Service detection nmap-top-20-udp on 10.10.186.59 returned non-zero exit code: 1`

Tried to run the nmap command manually and saw that it requires root access.

tried sudo autorecon <ipaddress> but got the following instead.
`Traceback (most recent call last):
  File "/home/kali/.local/bin/autorecon", line 5, in <module>
    from autorecon.autorecon import main
ModuleNotFoundError: No module named 'autorecon'`

This is my path after sudo
```
└─$ sudo echo $PATH
/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/home/kali/.local/bin
```

**Comment by samuel-emrys** [comment]
As mentioned in the [README](https://github.com/Tib3rius/AutoRecon#pipx), to run `autorecon` with `sudo` privileges you should execute with one of the following statements:
```
$ sudo env "PATH=$PATH" autorecon [OPTIONS]
$ sudo $(which autorecon) [OPTIONS]
```

Alternatively, follow the instructions to more permanently modify your root path. The command you've executed to show your path after sudo doesn't show your super user path. To show the super user path:

```
$ echo 'echo $PATH' | sudo sh
```

You should see that `/home/kali/.local/bin` isn't on your sudo path.

**Comment by crance** [comment]
For some reason it was giving the module not found error for me.

Nevertheless, I managed to fix the issue by running `pipx reinstall-all`. Guess something wrong happened at pipx level.
