### ISSUE TITLE
Package cannot be a url - pipx install

### ISSUE THREAD

**Issue by r34p3rlabs** [Tib3rius/AutoRecon#59]
Anyone else having issues when trying to install via pipx. I installed all the requirements and when I attempt to install the required pre-reqs and get this:

kali@kali:~$ sudo pipx install git+https://github.com/Tib3rius/AutoRecon.git
Package cannot be a url

**Comment by samuel-emrys** [comment]
Haven't been able to reproduce your error, but you shouldn't be using `sudo` to install using `pipx`. If that doesn't work, can you provide more information about the steps you followed

**Comment by r34p3rlabs** [comment]
Pretty much I did a copy paste of the commands on the site. Only thing I really did different was:
1. When running "sudo apt install python3-pip", had to run sudo apt update to find the package
2. Re-ran "python3 -m pip install --user pipx" after ensure paths just to validate paths were correct. 
3. At the end when trying to install via pipx, the command couldn't be found, so I installed pipx. 

I am using the latest ova from the site as well... Also, I didn't have any issue installing this on my mac, not sure if that matters, but I am using vmware workstation 15 on windows 10 2004 Build... 

**Command History:**

kali@kali:~$ **sudo apt install python3**

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for kali: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3 is already the newest version (3.8.2-3).
python3 set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
kali@kali:~$ **sudo apt install python3-pip**
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package python3-pip is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python3-pip' has no installation candidate
kali@kali:~$ **sudo apt update**
Get:1 http://kali.download/kali kali-rolling InRelease [30.5 kB]
Get:2 http://kali.download/kali kali-rolling/main amd64 Packages [16.6 MB]
Get:3 http://kali.download/kali kali-rolling/contrib amd64 Packages [100 kB]
Get:4 http://kali.download/kali kali-rolling/non-free amd64 Packages [199 kB]
Fetched 16.9 MB in 2s (8,177 kB/s)                   
Reading package lists... Done
Building dependency tree       
Reading state information... Done
562 packages can be upgraded. Run 'apt list --upgradable' to see them.
kali@kali:~$ **sudo apt install python3-pip**
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  python-pip-whl python3-wheel
The following NEW packages will be installed:
  python-pip-whl python3-pip python3-wheel
0 upgraded, 3 newly installed, 0 to remove and 562 not upgraded.
Need to get 2,078 kB of archives.
After this operation, 3,329 kB of additional disk space will be used.
Do you want to continue? [Y/n] **y**
Get:1 http://kali.download/kali kali-rolling/main amd64 python-pip-whl all 20.0.2-5kali1 [1,842 kB]
Get:2 http://kali.download/kali kali-rolling/main amd64 python3-wheel all 0.34.2-1 [24.0 kB]
Get:3 http://kali.download/kali kali-rolling/main amd64 python3-pip all 20.0.2-5kali1 [211 kB]
Fetched 2,078 kB in 1s (3,790 kB/s)   
Selecting previously unselected package python-pip-whl.
(Reading database ... 257891 files and directories currently installed.)
Preparing to unpack .../python-pip-whl_20.0.2-5kali1_all.deb ...
Unpacking python-pip-whl (20.0.2-5kali1) ...
Selecting previously unselected package python3-wheel.
Preparing to unpack .../python3-wheel_0.34.2-1_all.deb ...
Unpacking python3-wheel (0.34.2-1) ...
Selecting previously unselected package python3-pip.
Preparing to unpack .../python3-pip_20.0.2-5kali1_all.deb ...
Unpacking python3-pip (20.0.2-5kali1) ...
Setting up python3-wheel (0.34.2-1) ...
Setting up python-pip-whl (20.0.2-5kali1) ...
Setting up python3-pip (20.0.2-5kali1) ...
Processing triggers for man-db (2.9.3-2) ...
Processing triggers for kali-menu (2020.3.2) ...
kali@kali:~$ **python3 -m pip install --user pipx**
Collecting pipx
  Downloading pipx-0.15.5.1-py3-none-any.whl (41 kB)
     |████████████████████████████████| 41 kB 898 kB/s 
Collecting userpath>=1.4.1
  Downloading userpath-1.4.1-py2.py3-none-any.whl (14 kB)
Collecting argcomplete<2.0,>=1.9.4
  Downloading argcomplete-1.12.0-py2.py3-none-any.whl (38 kB)
Requirement already satisfied: packaging>=20.0 in /usr/lib/python3/dist-packages (from pipx) (20.3)
Requirement already satisfied: click in /usr/lib/python3/dist-packages (from userpath>=1.4.1->pipx) (7.0)
Requirement already satisfied: distro; platform_system == "Linux" in /usr/lib/python3/dist-packages (from userpath>=1.4.1->pipx) (1.5.0)
Installing collected packages: userpath, argcomplete, pipx
  WARNING: The script userpath is installed in '/home/kali/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.                                                                                                                        
  WARNING: The script pipx is installed in '/home/kali/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.                                                                                                                        
Successfully installed argcomplete-1.12.0 pipx-0.15.5.1 userpath-1.4.1
kali@kali:~$ **python3 -m pipx ensurepath**
Success! Added /home/kali/.local/bin to the PATH environment variable.
/home/kali/.local/bin has been been added to PATH, but you need to
    open a new terminal or re-login for this PATH change to take
    effect.

Consider adding shell completions for pipx. Run 'pipx completions' for
instructions.

You will need to open a new terminal or re-login for the PATH changes
to take effect.

Otherwise pipx is ready to go! ✨ 🌟 ✨
kali@kali:~$ **python3 -m pip install --user pipx**
Requirement already satisfied: pipx in ./.local/lib/python3.8/site-packages (0.15.5.1)
Requirement already satisfied: packaging>=20.0 in /usr/lib/python3/dist-packages (from pipx) (20.3)
Requirement already satisfied: userpath>=1.4.1 in ./.local/lib/python3.8/site-packages (from pipx) (1.4.1)
Requirement already satisfied: argcomplete<2.0,>=1.9.4 in ./.local/lib/python3.8/site-packages (from pipx) (1.12.0)
Requirement already satisfied: distro; platform_system == "Linux" in /usr/lib/python3/dist-packages (from userpath>=1.4.1->pipx) (1.5.0)
Requirement already satisfied: click in /usr/lib/python3/dist-packages (from userpath>=1.4.1->pipx) (7.0)
kali@kali:~$ **pipx install git+https://github.com/Tib3rius/AutoRecon.git**
bash: pipx: command not found
kali@kali:~$ **sudo apt install pipx**
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following package was automatically installed and is no longer required:
  libmpdec2
Use 'sudo apt autoremove' to remove it.
The following additional packages will be installed:
  libpython3.8 libpython3.8-dev libpython3.8-minimal libpython3.8-stdlib python3-venv python3.8 python3.8-dev python3.8-minimal python3.8-venv
Suggested packages:
  python3.8-doc
The following NEW packages will be installed:
  pipx python3-venv python3.8-venv
The following packages will be upgraded:
  libpython3.8 libpython3.8-dev libpython3.8-minimal libpython3.8-stdlib python3.8 python3.8-dev python3.8-minimal
7 upgraded, 3 newly installed, 0 to remove and 555 not upgraded.
Need to get 10.8 MB of archives.
After this operation, 381 kB disk space will be freed.
Do you want to continue? [Y/n] **y**
Get:1 http://kali.download/kali kali-rolling/main amd64 python3.8-dev amd64 3.8.5-2 [514 kB]
Get:2 http://kali.download/kali kali-rolling/main amd64 python3.8 amd64 3.8.5-2 [420 kB]
Get:3 http://kali.download/kali kali-rolling/main amd64 libpython3.8-dev amd64 3.8.5-2 [3,840 kB]
Get:4 http://kali.download/kali kali-rolling/main amd64 libpython3.8 amd64 3.8.5-2 [1,608 kB]
Get:5 http://kali.download/kali kali-rolling/main amd64 libpython3.8-stdlib amd64 3.8.5-2 [1,725 kB]
Get:6 http://kali.download/kali kali-rolling/main amd64 python3.8-minimal amd64 3.8.5-2 [1,865 kB]
Get:7 http://kali.download/kali kali-rolling/main amd64 libpython3.8-minimal amd64 3.8.5-2 [761 kB]
Get:8 http://kali.download/kali kali-rolling/main amd64 python3.8-venv amd64 3.8.5-2 [5,392 B]
Get:9 http://kali.download/kali kali-rolling/main amd64 python3-venv amd64 3.8.2-3 [1,180 B]
Get:10 http://kali.download/kali kali-rolling/main amd64 pipx all 0.12.3.1-3 [24.5 kB]
Fetched 10.8 MB in 1s (8,467 kB/s)
(Reading database ... 258094 files and directories currently installed.)
Preparing to unpack .../0-python3.8-dev_3.8.5-2_amd64.deb ...
Unpacking python3.8-dev (3.8.5-2) over (3.8.4-1) ...
Preparing to unpack .../1-python3.8_3.8.5-2_amd64.deb ...
Unpacking python3.8 (3.8.5-2) over (3.8.4-1) ...
Preparing to unpack .../2-libpython3.8-dev_3.8.5-2_amd64.deb ...
Unpacking libpython3.8-dev:amd64 (3.8.5-2) over (3.8.4-1) ...
Preparing to unpack .../3-libpython3.8_3.8.5-2_amd64.deb ...
Unpacking libpython3.8:amd64 (3.8.5-2) over (3.8.4-1) ...
Preparing to unpack .../4-libpython3.8-stdlib_3.8.5-2_amd64.deb ...
Unpacking libpython3.8-stdlib:amd64 (3.8.5-2) over (3.8.4-1) ...
Preparing to unpack .../5-python3.8-minimal_3.8.5-2_amd64.deb ...
Unpacking python3.8-minimal (3.8.5-2) over (3.8.4-1) ...
Preparing to unpack .../6-libpython3.8-minimal_3.8.5-2_amd64.deb ...
Unpacking libpython3.8-minimal:amd64 (3.8.5-2) over (3.8.4-1) ...
Selecting previously unselected package python3.8-venv.
Preparing to unpack .../7-python3.8-venv_3.8.5-2_amd64.deb ...
Unpacking python3.8-venv (3.8.5-2) ...
Selecting previously unselected package python3-venv.
Preparing to unpack .../8-python3-venv_3.8.2-3_amd64.deb ...
Unpacking python3-venv (3.8.2-3) ...
Selecting previously unselected package pipx.
Preparing to unpack .../9-pipx_0.12.3.1-3_all.deb ...
Unpacking pipx (0.12.3.1-3) ...
Setting up libpython3.8-minimal:amd64 (3.8.5-2) ...
Setting up python3.8-minimal (3.8.5-2) ...
Setting up libpython3.8-stdlib:amd64 (3.8.5-2) ...
Setting up python3.8 (3.8.5-2) ...
Setting up libpython3.8:amd64 (3.8.5-2) ...
Setting up python3.8-venv (3.8.5-2) ...
Setting up python3-venv (3.8.2-3) ...
Setting up libpython3.8-dev:amd64 (3.8.5-2) ...
Setting up python3.8-dev (3.8.5-2) ...
Setting up pipx (0.12.3.1-3) ...
Processing triggers for kali-menu (2020.3.2) ...
Processing triggers for desktop-file-utils (0.26-1) ...
Processing triggers for mime-support (3.64) ...
Processing triggers for libc-bin (2.30-8) ...
Processing triggers for man-db (2.9.3-2) ...
kali@kali:~$ **pipx install git+https://github.com/Tib3rius/AutoRecon.git**
Package cannot be a url

**Comment by r34p3rlabs** [comment]
Fixed.. ended up having to run : python3 -m pip install --user -U pipx

This updated the package and installed successfully
