### ISSUE TITLE
notes.txt file is quadruple-spaced

### ISSUE THREAD

**Issue by amlamarra** [Tib3rius/AutoRecon#6]
This isn't an "issue" so much as an annoyance. The notes.txt file (/results/<IP>/report/notes.txt) is quadruple-spaced. For example:

```
  1 [*] netbios-ns found on udp/137.
  2 
  3 
  4 
  5 [*] upnp found on udp/1900.
  6 
  7 
  8 
  9 [*] msrpc found on tcp/135.
 10 
 11 
 12 
 13 [*] netbios-ssn found on tcp/139.
```

**Comment by Tib3rius** [comment]
That's by design, so you can add notes. In the example above, you would enter a note on line 3, 7, and 11. Purely an aesthetic choice.

**Comment by amlamarra** [comment]
I guess I misunderstood what the notes.txt file was for. I thought they were just notes from autorecon for the user to review. My bad.
