### ISSUE TITLE
IPv6 support where possible

### ISSUE THREAD

**Issue by cyberpathogen2018** [Tib3rius/AutoRecon#65]
nmap supports ipv6 with a -6 flag. I know other tools may or may not support those addresses. 

in the following example, i've assigned the ipv6 address to a hostname in /etc/hosts...

$ sudo autorecon -o ipv6 --single-target ipv6target.local --nmap-append "-6"
[sudo] password for user: 
[!] ipv6target.local does not appear to be a valid IP address, IP range, or resolvable hostname.
[!] You must specify at least one target to scan!
[!] You cannot provide more than one target when scanning in single-target mode.

--disable-sanity-checks doesn't make a difference

**Comment by Tib3rius** [comment]
@cyberpathogen2018 this was actually easier to implement than I thought. Please check out the latest beta. Some of the plugins won't work, which is expected. All the ones based off Nmap (the majority) will though.
