### ISSUE TITLE
Make AutoRecon Accessible

### ISSUE THREAD

**Issue by bee-san** [Tib3rius/AutoRecon#73]
Hey Tib! It's I, [Bee from THM](https://twitter.com/bee_sec_san)!

I saw you're working on a new & improved AutoRecon and I wanted to suggest a feature.

A flag, `--accessible`, which tries to remove ascii art & make the program accessible to screenreaders / not have contrasting colours etc.

# Why?

Take this input (from the README):

```
$ autorecon 127.0.0.1
[*] Scanning target 127.0.0.1
[*] Running service detection nmap-full-tcp on 127.0.0.1
[*] Running service detection nmap-top-20-udp on 127.0.0.1
[*] Running service detection nmap-quick on 127.0.0.1
[*] Service detection nmap-quick on 127.0.0.1 finished successfully
[*] [127.0.0.1] ssh found on tcp/22
[*] [127.0.0.1] http found on tcp/80
[*] [127.0.0.1] rpcbind found on tcp/111
[*] [127.0.0.1] postgresql found on tcp/5432
[*] Running task tcp/22/nmap-ssh on 127.0.0.1
[*] Running task tcp/80/nmap-http on 127.0.0.1
[*] Running task tcp/80/curl-index on 127.0.0.1
[*] Running task tcp/80/curl-robots on 127.0.0.1
[*] Running task tcp/80/whatweb on 127.0.0.1
[*] Running task tcp/80/nikto on 127.0.0.1
[*] Running task tcp/111/nmap-nfs on 127.0.0.1
[*] Task tcp/80/curl-index on 127.0.0.1 finished successfully
[*] Task tcp/80/curl-robots on 127.0.0.1 finished successfully
[*] Task tcp/22/nmap-ssh on 127.0.0.1 finished successfully
[*] Task tcp/80/whatweb on 127.0.0.1 finished successfully
[*] Task tcp/111/nmap-nfs on 127.0.0.1 finished successfully
[*] Task tcp/80/nmap-http on 127.0.0.1 finished successfully
[*] Task tcp/80/nikto on 127.0.0.1 finished successfully
[*] Service detection nmap-top-20-udp on 127.0.0.1 finished successfully
[*] Service detection nmap-full-tcp on 127.0.0.1 finished successfully
[*] [127.0.0.1] http found on tcp/5984
[*] [127.0.0.1] rtsp found on tcp/5985
[*] Running task tcp/5984/nmap-http on 127.0.0.1
[*] Running task tcp/5984/curl-index on 127.0.0.1
[*] Running task tcp/5984/curl-robots on 127.0.0.1
[*] Running task tcp/5984/whatweb on 127.0.0.1
[*] Running task tcp/5984/nikto on 127.0.0.1
[*] Task tcp/5984/curl-index on 127.0.0.1 finished successfully
[*] Task tcp/5984/curl-robots on 127.0.0.1 finished successfully
[*] Task tcp/5984/whatweb on 127.0.0.1 finished successfully
[*] Task tcp/5984/nikto on 127.0.0.1 finished successfully
[*] Task tcp/5984/nmap-http on 127.0.0.1 finished successfully
[*] Finished scanning target 127.0.0.1
```

Here's a link to a TTS reading this:
https://drive.google.com/file/d/11mJN5YDrTBgMbqCPE2GKNyxUIRNqSuU1/view?usp=sharing

You can see that it pronounces the "*" as "asterisk", and in some TTs' it may pronounce the "[]" square brackets.

# Conclusion

It's important to make hacking accessible to all, and while AutoRecon is great -- the vast majority of hacking tools are not. See my blog post for more:
[https://polymath.cloud/a11y/](https://polymath.cloud/a11y/).

For example, Metasploit uses:
![image](https://user-images.githubusercontent.com/10378052/103177719-b0875f00-4874-11eb-869f-fc87146def6c.png)
And even in their "quiet" mode they still use ASCII art which destroys TTS.

By explicitly supporting an `--accessible` option in AutoRecon, I am hoping that other infosec tools follow suit and understand the need to make hacking accessible.

P.S. If you need a hand doing this, let me know! I know you're working on a new version of AutoRecon, so I don't want to submit a PR only for it to get over-written :) 

**Edit**: I know that the vast majority of tools used by AutoRecon are not accessible, but it's a nice step in the right direction! 😁

**Comment by Tib3rius** [comment]
Fixed in 70e6eec782b235d46b6258530a315fe65bdf7b45.
