### ISSUE TITLE
Profiles and Pipx

### ISSUE THREAD

**Issue by opsec-infosec** [Tib3rius/AutoRecon#77]
Issue with recognizing profiles when running with Pipx and sudo.

Profiles work when running without sudo, however when running with sudo, the profile are not recognized.

I think the autorecon uses a different profile location when using sudo (it should be under /home/\<user>/.config/AutoRecon

for example - 
$(which autorecon) --profile test 127.0.0.1 
This works, however

sudo $(which autorecon) --profile test 127.0.0.1
This does not work and autorecon complains about no profile found.

Contents of /home/\<user>/.config/AutoRecon/port-scan-profiles.toml

```text 
...

 [test]

    [test.nmap-quick]

        [test.nmap-quick.service-detection]
        command = 'nmap {nmap_extra} -sT -sC -sV --version-all -oN "{scandir}/_quick_tcp_nmap.txt" -oX "{scandir}/xml/_quick_tcp_nmap.xml" {address}'
        pattern = '^(?P<port>\d+)\/(?P<protocol>(tcp|udp))(.*)open(\s*)(?P<service>[\w\-\/]+)(\s*)(.*)$'

    [test.nmap-full-tcp]

        [sshuttle.nmap-full-tcp.service-detection]
        command = 'nmap {nmap_extra} -sT --osscan-guess --version-all  -p- -oN "{scandir}/_full_tcp_nmap.txt" -oX "{scandir}/xml/_full_tcp_nmap.xml" {address}'
        pattern = '^(?P<port>\d+)\/(?P<protocol>(tcp|udp))(.*)open(\s*)(?P<service>[\w\-\/]+)(\s*)(.*)$'

    [test.nmap-top-20-udp]

        [test.nmap-top-20-udp.service-detection]
        command = 'nmap -sU -A -Pn  --top-ports=20 --version-all -oN "{scandir}/_top_20_udp_nmap.txt" -oX "{scandir}/xml/_top_20_udp_nmap.xml" {address}'
        pattern = '^(?P<port>\d+)\/(?P<protocol>(tcp|udp))(.*)open(\s*)(?P<service>[\w\-\/]+)(\s*)(.*)$'

...
```

**Comment by Tib3rius** [comment]
Profiles have been removed in version 2, and pipx is not currently supported in that version either, so I'm closing this.

Version 2 code (beta) can be found here: https://github.com/Tib3rius/AutoRecon/tree/beta
