### ISSUE TITLE
Can't type in terminal after runing autorecon

### ISSUE THREAD

**Issue by key-equivalent** [Tib3rius/AutoRecon#79]
After running AutoRecon and either letting it finish successfully or interrupting with ctrl+C, it will no longer accept input in that terminal other than ctrl+C which enters ^C and goes to a new line.  Opening a new tab or window gets you going again but I haven't found any way to recover the original terminal that autorecon ran in.  

This happens on standard kali2020 as well as the PWK2020 VM.  It happens with pip or manual installation.  pipx would not work on the PWK vm

**Comment by mcbazza** [comment]
Type 'reset' (you won't see it echo) and you'll have that terminal session back.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by key-equivalent** [comment]
Thanks!  That worked
