### ISSUE TITLE
Custom Config File

### ISSUE THREAD

**Issue by n0bfu** [Tib3rius/AutoRecon#8]
Sometimes there are reasons to have modified or added custom scans. Currently the only way to have those run is to modify port-scan-profiles.toml or service-scans.toml files. Unfortunately these changes are lost, unless backed up, each update and then the files must be manually compared to fixes. 

A "customs" file in the config directory which is referenced would allow these custom scans to be ran in addition to or to replace the default scans included with a default install. The config file would not be updated with each revision allowing the custom scans to remain.

Possible solution:
Referencing the customs file, but not including it in the git so a fresh pull won't overwrite the customs file. A user would just have to create and properly name the file to match what the default install is looking for.

**Comment by Tib3rius** [comment]
I agree with the suggestion. I will try to implement this in the next major release.
