### ISSUE TITLE
smbmap scan results display syntax warnings

### ISSUE THREAD

**Issue by srivathsa-tech** [Tib3rius/AutoRecon#80]
I tried running the autorecon on the HTB legacy machine with IP 10.10.10.4 and all the smbmap scan outputs have this syntax warnings. Please check.

┌──(kali㉿kali)-[~/…/legacy/results/10.10.10.4/scans]
└─$ cat smbmap-execute-command.txt 
/usr/lib/python3/dist-packages/impacket/smbserver.py:2464: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if jtr_dump_path is not '':
/usr/lib/python3/dist-packages/impacket/smbserver.py:2500: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if jtr_dump_path is not '':
/usr/lib/python3/dist-packages/impacket/smbserver.py:2842: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if jtr_dump_path is not '':
/usr/lib/python3/dist-packages/impacket/smbserver.py:4416: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if credentials_fname is not "":
[!] RPC Authentication error occurred
[!] Authentication error on 10.10.10.4

**Comment by Tib3rius** [comment]
This looks more like an impacket error, and without any context it's difficult to know why this happened. Have had no other complaints about smbmap.
