### ISSUE TITLE
gobuster version (3.1.0-0kali1 ) no longer has "-l flag"

### ISSUE THREAD

**Issue by djinnsec** [Tib3rius/AutoRecon#83]
gobuster keeps failing : 
Task tcp/80/gobuster returned non-zero exit code: 1. 

Error: unknown shorthand flag: 'l' in -l
i've installed autorecon using the pipx method.

**Comment by fachizel** [comment]
same, would manually removing the -l flags work?

**Comment by ajohnson5498** [comment]
I finally figured this out just in time for my exam tomorrow. Yes removing the -l flag does work, but not in the service-scans-default.toml file inside the config folder. The file path for me was /root/.config/AutoRecon/service-scans.toml

Deleting the '-l 'flag on line 134 did the trick for me. Note that it runs another gobuster command on the same line if the conditional if statement fails for whatever reason so I deleted both.

**Comment by rishabhmishra25** [comment]
This solves the problem precisely, removing the -l flag from all its occourance solves the issue.

**Comment by kastahl** [comment]
Yeah, confirm. Removing all -l flag gives no error anymore.
Thx @ajohnson5498 for the hint.

**Comment by Tib3rius** [comment]
Fixed in fb9ca7e.
