### ISSUE TITLE
Issue with gobuster failing

### ISSUE THREAD

**Issue by somerandomdudeonetheinternet** [Tib3rius/AutoRecon#84]
I was doing *the* exam yesterday, and gobuster launched by autorecon failed on every host. Although my manual execution of gobuster worked fine. I updated kali recently before the exam, so not sure if that broke something. It gave me something along the lines of "gobuster ... error returned with [1]" (not the exact error message). Just thought it would mention the issue in case anyone else experiences problems with the latest kali updates

**Comment by trb143** [comment]
See issue https://github.com/Tib3rius/AutoRecon/issues/83

**Comment by robsware** [comment]
Also see my fork and lines about removing the default config files:
https://github.com/Tib3rius/AutoRecon/issues/69#issuecomment-787828586

**Comment by Tib3rius** [comment]
Closing since 1486210 removed gobuster from the automated scans.
