### ISSUE TITLE
asyncio

### ISSUE THREAD

**Issue by drforbin** [Tib3rius/AutoRecon#89]
Anyone wanna get together and rewrite asyncio out of this great tool?
asyncio will be removed in python 3.11

????

**Comment by Tib3rius** [comment]
This is incorrect, asyncio isn't being removed, but passing coroutine objects to asyncio.wait() is being removed. I have plans to fix this but python 3.11 is several years away so I have some time. This will be fixed as part of a general rewrite of the entire tool.
